name: vanilla cmake

on: [push, pull_request]

jobs:

  ubuntu-build-test:
    runs-on: ${{ matrix.ubuntu-distro }}
    strategy:
      fail-fast: false
      matrix:
        ubuntu-distro:
          - ubuntu-20.04
          - ubuntu-22.04

    steps:
      - name: Sync repository
        uses: actions/checkout@v2

      - name: Install apt packages
        run: |
              sudo apt update && sudo apt -y install \
                software-properties-common \
                qtbase5-dev \
                libqt5svg5-dev \
                libqt5websockets5-dev \
                libqt5opengl5-dev \
                libqt5x11extras5-dev \
                libprotoc-dev \
                libzmq3-dev

      - name: Build workspace
        run: |
            cmake -B build\plotjuggler PlotJuggler;
            cmake --build build\plotjuggler --target install
