name: cmake

on: [push, pull_request]

jobs:

  macos-build:
    runs-on: ${{ matrix.macos-version }}
    strategy:
      fail-fast: false
      matrix:
        macos-version:
          - 'macos-latest'

    steps:
      - name: Sync repository
        uses: actions/checkout@v2

      - name: Install Qt
        uses: jurplel/install-qt-action@v2.13.0
        with:
          version: '5.15.2'
          host: 'mac'
          dir: '${{ github.workspace }}/qt_installation/'

      - name: Build Plotjuggler
        shell: pwsh
        run: >
          cmake -B build -DCMAKE_INSTALL_PREFIX=install PlotJuggler;
          cmake --build build --target install
