name: ros2-rolling

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ros:rolling
    steps:

      # Step 3: Run ROS CI
      - uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: plotjuggler
          target-ros2-distro: rolling
