name: ros2-humble

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ros:humble
    steps:

      - uses: ros-tooling/action-ros-ci@v0.4
        with:
          package-name: plotjuggler
          target-ros2-distro: humble
