name: windows

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, closed]

jobs:

  windows-build:
    runs-on: ${{ matrix.windows-version }}
    strategy:
      fail-fast: false
      matrix:
        windows-version:
          - 'windows-2019'
    env:
      CXXFLAGS: /MP

    steps:
      - name: Sync repository
        uses: actions/checkout@v4

      - name: Install Conan
        uses: turtlebrowser/get-conan@main

      - name: Cache Qt and Conan
        uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/qt_installation/
            ~/.conan/data
          key: ${{ runner.os }}-${{ hashFiles('**/qt_installation/**', '**/conanfile.txt') }}
          restore-keys: ${{ runner.os }}-

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '5.15.2'
          arch: 'win64_msvc2019_64'
          dir: '${{ github.workspace }}/qt_installation/'
          cache: 'true'
          cached: ${{ steps.cache-qt.outputs.cache-hit }}
          tools: 'tools_ifw'
          add-tools-to-path: true

      - name: Setup ccache
        uses: Chocobo1/setup-ccache-action@v1
        with:
          windows_compile_environment: msvc  # this field is required

      - name: Build Plotjuggler
        shell: pwsh
        run: >
          conan profile detect;
          conan install . -of build --build=missing -pr:b=default -s build_type=Release;
          cmake `
          -G "Visual Studio 16 2019"  `
          -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake
          -Ax64 -T host=x64 `
          -B build `
          -DCMAKE_CXX_COMPILER_LAUNCHER:FILEPATH="${{ env.ccache_symlinks_path }}" `
          -DCMAKE_INSTALL_PREFIX=install `
          -DCMAKE_POLICY_DEFAULT_CMP0091=NEW `
          .;
          cmake --build build --config Release --target install

      - name: Build QT Installer
        # if: github.event_name == 'release' || github.event.inputs.run-installer == 'true'
        shell: pwsh
        run: >
          xcopy src/PlotJuggler/installer installer/ /Y /S /f /z;
          xcopy install/bin/*.* installer/io.plotjuggler.application/data /Y /S /f /z;
          windeployqt.exe --release installer/io.plotjuggler.application/data/PlotJuggler.exe;
          binarycreator.exe --offline-only -c installer\config.xml -p installer PlotJuggler-Windows-installer.exe

      - name: Upload installer
        if: github.event_name == 'release' || github.event.inputs.run-installer == 'true'
        uses: softprops/action-gh-release@v1
        with:
          files: PlotJuggler-Windows-installer.exe
