name: windows

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, closed]

jobs:

  windows-build:
    runs-on: ${{ matrix.windows-version }}
    strategy:
      fail-fast: false
      matrix:
        windows-version:
          - 'windows-latest'
    env:
      CXXFLAGS: /MP

    steps:
      - name: Sync repository
        uses: actions/checkout@v4

      - name: Install Conan
        uses: turtlebrowser/get-conan@main

      - name: Cache Qt and Conan
        uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/qt_installation/
            ~/.conan2/
          key: ${{ runner.os }}-${{ hashFiles('**/qt_installation/**', '**/conanfile.txt') }}
          restore-keys: ${{ runner.os }}-

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '5.15.2'
          arch: 'win64_msvc2019_64'
          dir: '${{ github.workspace }}/qt_installation/'
          cache: 'true'
          cached: ${{ steps.cache-qt.outputs.cache-hit }}
          tools: 'tools_ifw'

      - name: Conan install
        shell: pwsh
        run: |
          conan profile detect
          conan install . -of build --build=missing -pr:b=default -s build_type=Release

      - name: Build Plotjuggler
        shell: pwsh
        run: |
          cmake --preset conan-default -B build -DBUILDING_WITH_CONAN=ON -DCMAKE_INSTALL_PREFIX=install -DCMAKE_BUILD_TYPE=Release .
          cmake --build build --config Release --target install

      - name: Create installer using QT Installation Framework
        id: create_installer
        shell: pwsh
        run: |
          xcopy install\lib\*.* installer\io.plotjuggler.application\data\lib /Y /S /f /z
          windeployqt.exe --release installer\io.plotjuggler.application\data\plotjuggler.exe
          $tag = "${{ github.ref_name }}"
          $installerName = "PlotJuggler-Windows-installer-$tag.exe"
          binarycreator.exe --offline-only -c installer\config.xml -p installer $installerName
          echo "installer_name=$installerName" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

      - name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.create_installer.outputs.installer_name }}
          path: ${{ steps.create_installer.outputs.installer_name }}
